export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const LOGOFF = "LOGOFF";
export const SET_CUSTOMER_POLICIES = "SET_CUSTOMER_POLICIES";
export const ADD_CUSTOMER_POLICY = "ADD_CUSTOMER_POLICY";